#!/bin/bash

DATAVOL=/var/lib/openvas/mgr/
OV_PASSWORD=${OV_PASSWORD:-admin}
WEB_CERT_FILE=${WEB_CERT_FILE:-""}
WEB_KEY_FILE=${WEB_KEY_FILE:-""}

if [ ! -z "$WEB_CERT_FILE" -a ! -z "$WEB_KEY_FILE" ]; then 
        echo 'DAEMON_ARGS="--mlisten 127.0.0.1 -m 9390 -k '$WEB_KEY_FILE' -c '$WEB_CERT_FILE'"' >> /etc/default/openvas-gsa
fi

redis-server /etc/redis/redis.conf

echo "Testing redis status..."
X="$(redis-cli ping)"
while  [ "${X}" != "PONG" ]; do
        echo "Redis not yet ready..."
        sleep 1
        X="$(redis-cli ping)"
done
echo "Redis ready."

echo "Checking for empty volume"
[ -e "$DATAVOL/tasks.db" ] || SETUPUSER=true

echo "Restarting services"
service openvas-scanner restart
service openvas-manager restart
service openvas-gsa restart

echo "Reloading NVTs"
openvasmd --rebuild --progress

if [ -n "$SETUPUSER" ]; then
  echo "Setting up user"
  /usr/sbin/openvasmd openvasmd --create-user=admin
  /usr/sbin/openvasmd --user=admin --new-password=$OV_PASSWORD
fi

echo "Checking setup"
./openvas-check-setup --v9

if [ -z "$BUILD" ]; then
  echo "Tailing logs"
  tail -F /var/log/openvas/*
fi
