#!/bin/bash

DATAVOL=/var/lib/openvas/mgr/
OV_PASSWORD=${OV_PASSWORD:-admin}

redis-server /etc/redis/redis.conf

echo "Testing redis status..."
X="$(redis-cli ping)"
while  [ "${X}" != "PONG" ]; do
        echo "redis not yet ready"
        sleep 1
        X="$(redis-cli ping)"
done
echo "Redis ready."

echo "Checking for empty volume"
[ -e "$DATAVOL/tasks.db" ] || SETUPUSER=true

echo "Services configuration"
sed -i 's/DAEMON_ARGS=""/DAEMON_ARGS="-a 0.0.0.0"/' /etc/init.d/openvas-manager
sed -i 's/DAEMON_ARGS=""/DAEMON_ARGS="--mlisten 127.0.0.1 -m 9390"/' /etc/init.d/openvas-gsa

echo "Restarting services"
service openvas-scanner restart
service openvas-manager restart
service openvas-gsa restart

echo "Reloading NVTs"
openvasmd --rebuild --progress

if [ -n "$SETUPUSER" ]; then
  echo "Setting up user"
  /usr/sbin/openvasmd openvasmd --create-user=admin
  /usr/sbin/openvasmd --user=admin --new-password=$OV_PASSWORD
fi

echo "Checking setup"
./openvas-check-setup --v9

if [ -z "$BUILD" ]; then
  echo "Tailing logs"
  tail -F /var/log/openvas/*
fi
