#!/usr/bin/with-contenv sh

PY3VER=`python3 --version | grep -o [0-9]\.[0-9]`
export PYTHONPATH=/opt/gvm/lib/python$PY3VER/site-packages

touch /opt/gvm/ospd.conf

s6-setuidgid gvm /usr/bin/python3 /opt/gvm/bin/ospd-openvas --pid-file /opt/gvm/var/run/ospd-openvas.pid --log-file /opt/gvm/var/log/gvm/ospd-openvas.log --lock-file-dir /opt/gvm/var/run -u /opt/gvm/var/run/ospd.sock -s /opt/gvm/ospd.conf